version: '3'

services:
  app:
    container_name: app
    build: ./.docker/php/
    volumes:
      - ./src:/var/www/html
      - vendor:/var/www/html/vendor
      - node_modules:/var/www/html/node_modules
  web:
    container_name: web
    image: nginx:1.21-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  db:
    container_name: db
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./.docker/pgsql:/var/dump
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=sample_db
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --locale=ja_JP.UTF-8


volumes:
  vendor:
  node_modules:
  db:
